module.exports = [
  { type: 'image', src: '/images/me-smiling.jpg' },
  { type: 'video', src: '/videos/bouldering.mp4' },
  { type: 'image', src: '/images/me-and-julia.jpg' },
  { type: 'video', src: '/videos/dancing.mp4' },
  { type: 'video', src: '/videos/bench.mp4' },
  { type: 'image', src: '/images/me-and-mom.jpg' },
  { type: 'video', src: '/videos/play-cle-1.mp4' },
  { type: 'image', src: '/images/me-and-sam.jpg' },
  { type: 'video', src: '/videos/play-cle-2.mp4' },
  { type: 'image', src: '/images/me-and-sisters.jpg' },
  { type: 'image', src: '/images/me-drawing.jpg' },
  { type: 'video', src: '/videos/me-and-jack.mp4' },
  { type: 'image', src: '/images/me-and-dad.jpg' },
  { type: 'image', src: '/images/me-and-jamie.jpg' },
  { type: 'video', src: '/videos/we-will-rock-you.mp4' },
]
